### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by wangwenx190** [deepin-community/sig-deepin-qt#2]
作为业余爱好使用Qt开发Windows平台应用程序多年，近年来也开始尝试迁移至macOS。对Qt源码定制修改颇感兴趣，因此申请加入此群组。

我为Qt提交的所有代码：<https://codereview.qt-project.org/q/owner:2546789017%2540qq.com>。因个人喜爱定制个性化的Qt，所以对Qt源码有一定程度的了解。

**Comment by Dami-star** [comment]
在codereview上经常看到你的提交，质量很高 ，欢迎你的加入，稍后我会添加你进入小组。

**Comment by Dami-star** [comment]
> 作为业余爱好使用Qt开发Windows平台应用程序多年，近年来也开始尝试迁移至macOS。对Qt源码定制修改颇感兴趣，因此申请加入此群组。
> 
> 我为Qt提交的所有代码：https://codereview.qt-project.org/q/owner:2546789017%2540qq.com。因个人喜爱定制个性化的Qt，所以对Qt源码有一定程度的了解。

已正式添加你进入deepin-qt https://github.com/deepin-community/SIG/pull/47,欢迎多使用deepin给我们提交任何Qt相关问题和想法。

**Comment by wangwenx190** [comment]
非常感谢😁
